### PR TITLE
Reduce argument allocations for checkArgument to reduce gc pressure.

### PR DESCRIPTION
**Pull request by david-ry4n**
## PR description
The checkArgument( boolean, String, ... ) causes a large number of Integer and int[] to be created temporarily on the heap which causes gc pressure. This PR adds overloads which reduces object allocations to 0 for these method calls.

### CODE REVIEW

**Review by ahamlat — APPROVED** [review]
Nice catch.

**Comment by ahamlat** [comment]
You will need to run spotless.

**Comment by macfarla** [comment]
@atoulme improvement for memory allocation - are you accepting PRs into this project?

**Review by atoulme — APPROVED** [review]

**Comment by macfarla** [comment]
looks like the GPG signing key has expired @atoulme

**Comment by atoulme** [comment]
I'll take a look.

**Comment by david-ry4n** [comment]
@atoulme would it be possible to get write access for me and a few others on this repo? Would like to get this change merged and be able to do releases when required.

**Comment by macfarla** [comment]
@atoulme this PR includes groupid change in build.gradle which is going to cause issues when publishing

**Pull request merged**
